version: 2
jobs:
  update_addresses:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          command: |
            poetry install
            cp stadfangaskra.csv stadfangaskra-old.csv
            poetry run addresses > stadfangaskra.csv
            git add stadfangaskra.csv
            git config --global user.email "stadfangaskrarbot@example.com"
            git config --global user.name "Staðfangaskrárbot"
            poetry run csv-diff stadfangaskra-old.csv stadfangaskra.csv --key=HNITNUM --singular=address --plural=addresses > message.txt
            echo $'\n[skip ci]' >> message.txt
            git commit -F message.txt && \
              git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/flother/stadfangaskra.git master \
              || true
workflows:
  version: 2
  build:
    jobs:
      - update_addresses
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update_addresses
